### ISSUE TITLE
3.0.0 TODO

### ISSUE THREAD

**Issue by mgold** [mgold/elm-random-pcg#6]
On the `bit32` branch:
- [x] Implement 32 bits of state algorithm
- [x] Restore JSON and `fastForward`
- [x] Update README
- [x] Add `generate` - I think @rtfeldman had a PR?
- [x] Restore `independentSeed`
- [x] Statistical tests for random increments (independent seeds)
- [x] Statistical tests for default increment
- [x] Preliminary perf tests
- [x] Robust perf tests - Core
- [x] Robust perf tests - PCG-64
- [x] Robust perf tests - PCG-32
- [x] Robust perf tests - PCG-32-JS
- [x] Tabulate perf test results
- [x] Report all test results
- [ ] Merge into master and release

**Comment by mgold** [comment]
3.0.0 released!
